### ISSUE TITLE
dmenu for the command buffer

### ISSUE THREAD

**Issue by Superpat** [sminez/ad#25] opened 2024-10-03 15:28 UTC
### Please describe the change / addition you'd like to see made

- Is this completely new functionality, or an enhancement to existing functionality?
Applies existing functionality to a new area

- What kind of feature is it that you are requesting?
I feel that the dmenu like filtering you have in the buffer text search should also apply to the mini-buffer when in command mode, so I can organically discover the possible commands.

### Is this a feature you have seen in other text editors?

Kind of similar to kakounes clippy

**Comment by sminez** [comment] 2024-10-03 16:11
hey @Superpat, thanks for raising this! I've got this covered already I think in https://github.com/sminez/ad/issues/15 ? The title of that issue doesn't help with finding it if you are specifically after the dmenu-like functionality though so I'll update it to make things clearer.

I'm also wanting to add something similar to the `run` mode so you can filter through your history within a single session and / or autocomplete paths of programs that are in `~/.ad/bin`.

**Comment by sminez** [comment] 2024-10-03 16:12
Closing as a duplicate of #15

**Closed as not planned by sminez** 2024-10-03 16:12 UTC
Labels: enhancement
