### ISSUE TITLE
tabs confuse ad (or me)

### ISSUE THREAD

**Issue by srenatus** [sminez/ad#34] opened 2024-10-11 10:41 UTC
### Describe the bug

When a line of text starts with a tab character, everything seems to be off by one.

### To Reproduce

Create a file with this content
```
	THIS line has a tab
    THIS line has 4 spaces
```

Move the cursor on the first THIS' "T", press "W":

<img width="293" alt="image" src="https://github.com/user-attachments/assets/fb0e183e-5bf9-4725-9031-0ef3dc9770ab">

Move the cursor on the second THIS' "T", press "W":

<img width="272" alt="image" src="https://github.com/user-attachments/assets/10579bc9-acb4-4e38-b721-672c51e370e3">

### Expected behavior

Both outcomes should be the same, but the tab-line has everything shifted by a character.

### Versions & OS Details

- OS: macos 14.7
- ad Version 7506b582b41304e0812aad24f3417ddfce419e57

**Comment by sminez** [comment] 2024-10-11 10:51
I think that this is a UI issue around determining where to highlight the dot rather than something wrong with the actual internal state. So something [here](https://github.com/sminez/ad/blob/develop/src/buffer/mod.rs#L642-L648) I suspect? If you try deleting the selection in the steps you describe above (so, `Wd` instead of just `W`) you should see that it correctly deletes "This".

**Comment by srenatus** [comment] 2024-10-11 11:44
> If you try deleting the selection in the steps you describe above (so, Wd instead of just W) you should see that it correctly deletes "This".

Yup, I saw that, too.

**Comment by srenatus** [comment] 2024-10-11 12:10
FWIW it's one char per tab that's off -- this line starts with two tab characters:

<img width="292" alt="image" src="https://github.com/user-attachments/assets/2b217fac-1e3c-4ab8-bdd3-c9360cf97fa5">

**Comment by sminez** [comment] 2024-10-11 13:08
yeah that makes sense if the issue is what I suspect it is. I'll try and take a look this evening when I have some free time :slightly_smiling_face:

**Comment by sminez** [comment] 2024-10-11 21:54
@srenatus that should be fixed now in the commit shown above. It turns out I even had a test for this...I just set up the test data incorrectly :facepalm:

**Closed as completed** 2024-10-11 21:53 UTC
Labels: bug

**Comment by srenatus** [comment] 2024-10-12 07:49
Just tried it -- it works as expected now, thank you! 🎈

**Comment by sminez** [comment] 2024-10-12 09:31
Thank you for confirming and for raising the bug in the first place 🙂
